name: publish

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: kagw-app-reeldeal
  AZURE_WEBAPP_PACKAGE_PATH: './publish' # Set this to the path to your web app project, defaults to the repository root:
  DOTNET_VERSION: '6.0.100' # The .NET SDK version to use

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build
      run: |
        dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }} -r linux-x64 --self-contained true /p:UseAppHost=true
    
    - uses: azure/PublishPipelineArtifact@1
      name: download artiffact
      with: 
        targetPath: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        artifactName: ${{ env.AZURE_WEBAPP_NAME }}

      
    - uses: azure/webapps-deploy@v2
      name: Deploy
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}